// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-ddd-seed/go-ddd-seed/internal/application/commandHandler"
	"github.com/go-ddd-seed/go-ddd-seed/internal/application/queryService"
	"github.com/go-ddd-seed/go-ddd-seed/internal/infrastructure/adapter/repo"
	"github.com/go-ddd-seed/go-ddd-seed/internal/infrastructure/adapter/thirdPartyApi/storage"
	"github.com/go-ddd-seed/go-ddd-seed/internal/infrastructure/messaging"
	"github.com/go-ddd-seed/go-ddd-seed/internal/infrastructure/persistence"
	"github.com/go-ddd-seed/go-ddd-seed/internal/trigger/http/controller"
	"github.com/go-ddd-seed/go-ddd-seed/pkg/config"
)

import (
	_ "github.com/go-ddd-seed/go-ddd-seed/docs/swagger"
)

// Injectors from wire.go:

// InitializeApp 通过 Wire 注入依赖
func InitializeApp(cfg *config.Config) (*App, func(), error) {
	databaseConfig := provideDatabaseConfig(cfg)
	db, err := persistence.NewDatabase(databaseConfig)
	if err != nil {
		return nil, nil, err
	}
	redisConfig := provideRedisConfig(cfg)
	client, err := persistence.NewRedisClient(redisConfig)
	if err != nil {
		return nil, nil, err
	}
	healthController := controller.NewHealthController()
	loggerAdapter := messaging.NewWatermillLogger()
	goChannel := messaging.NewGoChannelPubSub(loggerAdapter)
	jsonMarshaler := messaging.NewJSONMarshaler()
	watermillEventBus := messaging.NewWatermillEventBus(goChannel, jsonMarshaler, loggerAdapter)
	repositoryBase := repo.NewRepositoryBase(db, watermillEventBus)
	kvConfigRepository := repo.NewKvConfigRepository(repositoryBase)
	kvConfigReadRepository := repo.NewKvConfigReadRepository(db)
	kvConfigCommandHandler := commandHandler.NewKvConfigCommandHandler(kvConfigRepository)
	kvConfigQueryService := queryService.NewKvConfigQueryService(kvConfigReadRepository)
	kvConfigController := controller.NewKvConfigController(kvConfigCommandHandler, kvConfigQueryService)
	dictTypeRepository := repo.NewDictTypeRepository(repositoryBase)
	dictTypeReadRepository := repo.NewDictTypeReadRepository(db)
	dictCacheRepository := repo.NewDictCacheRepository(client, dictTypeReadRepository)
	dictCommandHandler := commandHandler.NewDictCommandHandler(dictTypeRepository, dictCacheRepository)
	dictQueryService := queryService.NewDictQueryService(dictTypeReadRepository, dictCacheRepository)
	dictController := controller.NewDictController(dictCommandHandler, dictQueryService)
	userRepository := repo.NewUserRepository(repositoryBase)
	userReadRepository := repo.NewUserReadRepository(db)
	roleReadRepository := repo.NewRoleReadRepository(db)
	jwtConfig := provideJWTConfig(cfg)
	authCommandHandler := commandHandler.NewAuthCommandHandler(userRepository, userReadRepository, roleReadRepository, client, jwtConfig)
	authController := controller.NewAuthController(authCommandHandler)
	roleRepository := repo.NewRoleRepository(repositoryBase)
	permissionRepository := repo.NewPermissionRepository(repositoryBase)
	rbacCommandHandler := commandHandler.NewRbacCommandHandler(roleRepository, permissionRepository, userRepository)
	roleQueryService := queryService.NewRoleQueryService(roleReadRepository)
	permissionReadRepository := repo.NewPermissionReadRepository(db)
	permissionQueryService := queryService.NewPermissionQueryService(permissionReadRepository)
	userQueryService := queryService.NewUserQueryService(userReadRepository)
	rbacController := controller.NewRbacController(rbacCommandHandler, roleQueryService, permissionQueryService, userQueryService)
	auditLogRepository := repo.NewAuditLogRepository(db)
	auditLogQueryService := queryService.NewAuditLogQueryService(auditLogRepository)
	auditController := controller.NewAuditController(auditLogQueryService)
	fileRecordRepository := repo.NewFileRecordRepository(repositoryBase)
	storageConfig := provideStorageConfig(cfg)
	fileStorage, err := storage.NewFileStorage(storageConfig)
	if err != nil {
		return nil, nil, err
	}
	string2 := provideStorageChannel(storageConfig)
	fileCommandHandler := commandHandler.NewFileCommandHandler(fileRecordRepository, fileStorage, string2)
	fileRecordReadRepository := repo.NewFileRecordReadRepository(db)
	fileRecordQueryService := queryService.NewFileRecordQueryService(fileRecordReadRepository)
	fileController := controller.NewFileController(fileCommandHandler, fileRecordQueryService, fileStorage)
	app := NewApp(cfg, db, client, healthController, kvConfigController, dictController, authController, rbacController, auditController, fileController, auditLogRepository)
	return app, func() {
	}, nil
}

// wire.go:

// provideDatabaseConfig 从 Config 中提取 DatabaseConfig
func provideDatabaseConfig(cfg *config.Config) *config.DatabaseConfig {
	return &cfg.Database
}

// provideRedisConfig 从 Config 中提取 RedisConfig
func provideRedisConfig(cfg *config.Config) *config.RedisConfig {
	return &cfg.Redis
}

// provideJWTConfig 从 Config 中提取 JWTConfig
func provideJWTConfig(cfg *config.Config) *config.JWTConfig {
	return &cfg.JWT
}

// provideStorageConfig 从 Config 中提取 StorageConfig
func provideStorageConfig(cfg *config.Config) *config.StorageConfig {
	return &cfg.Storage
}

// provideStorageChannel 从 StorageConfig 中提取存储渠道标识
func provideStorageChannel(cfg *config.StorageConfig) string {
	return cfg.Driver
}
